spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aula_db?createDatabaseIfNotExist=true
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      maximum-pool-size: 20
      connection-timeout: 172800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update